[package]
name = "corecrunch"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
prettytable-rs = "0.10"
rayon = "1.8"
rand = "0.8"
sysinfo = "0.30"
sha2 = "0.10"
num_cpus = "1.0"
flate2 = "1.0"